// Kata's own exercise cards: a blurb, numbered steps and what to watch for, in our words. The full lessons live on
// drawabox.com and each card links there. Keyed by exercise id from curricula/drawabox.json.

const REF = [['Pick a reference.', 'High resolution, one subject, good light. Draw from the photo, not from memory.'], ['Find the big forms first.', 'Boxes, cylinders, sausages. Draw through them so they feel solid.'], ['Build in passes.', 'Add the next form only when the last one feels solid. No sketching, no clean-up pass.'], ['Stop before detail.', 'Construction is the exercise. Texture only if the card allows it.']];
const REF_WATCH = 'Flat shapes pasted on each other mean you skipped the drawing-through. Wobbly contours mean you drew too slowly.';

export const CARDS = {
  'l0-read': { blurb: 'Before the first line: why the course works the way it does, the 50% rule, how warm-ups fit in, and which pen and paper to use.', steps: [['Read Lesson 0 in one sitting.', 'About fifteen minutes.'], ['Decide on paper or tablet.', 'Kata does not care which. Drawabox recommends fineliner on printer paper.'], ['Note the 50% rule.', 'Half of your drawing time is for drawing whatever you want, outside the course.']], watch: 'Skipping it is the most common way to misread everything after it.' },

  'l1-superimposed': { blurb: 'Draw a line, then draw over it again and again from the same start point. It teaches your arm what a confident stroke feels like.', steps: [['Draw one line.', 'Any length, straight or curved. This is the guide.'], ['Return to its start.', 'Place the pen exactly on the first dot every time.'], ['Draw over it eight times.', 'Same speed, same commitment. Let the far end fray. Do not slow down to match.']], watch: 'Fraying at both ends means you did not start on the dot. Fraying at the far end only is correct.' },
  'l1-ghostedlines': { blurb: 'The one habit everything else depends on: decide the line first, then draw it once, from the shoulder, without slowing down to aim.', steps: [['Mark two dots.', 'Decide where the line starts and ends before the pen touches the page.'], ['Ghost it.', 'Move the pen along the path three or four times, hovering just above the paper.'], ['Draw once.', 'One confident stroke at the same speed as the ghosting. Do not slow down near the end.'], ['Leave it.', 'A wobble or a miss is information. Never go back over a line.']], watch: 'Wobbly lines mean you drew too slowly. Curved lines mean the wrist took over. Overshooting the dot is fine for now.' },
  'l1-ghostedplanes': { blurb: 'Four-sided planes drawn entirely with ghosted lines, then split by their diagonals and centre lines. Every line is planned.', steps: [['Place four dots.', 'A loose quadrilateral, any shape.'], ['Connect them with ghosted lines.', 'Plan, ghost, draw once. Every edge on its own.'], ['Add the diagonals and centre lines.', 'They should cross near the middle. Do not force it.'], ['Fill the page.', 'Big and small planes, no overlaps.']], watch: 'Same rules as ghosted lines. If the diagonals miss the centre by a lot, the plane was rushed.' },
  'l1-tables': { blurb: 'Rows of ellipses packed tight, each drawn through two or three times. It trains a smooth, confident ellipse and makes you commit to a size.', steps: [['Draw a table.', 'A grid of rows and cells with ghosted lines.'], ['Fill each row with ellipses.', 'They touch their neighbours and the row edges. Same degree and angle within a cell.'], ['Draw through.', 'Two or three passes around each ellipse, ghosting first, at a confident speed.'], ['Vary the cells.', 'Narrow, wide, tilted. Keep them consistent within one cell.']], watch: 'Pointy ends mean you are drawing from the wrist. Gaps between ellipses mean you are not committing to the size.' },
  'l1-ellipsesinplanes': { blurb: 'One ellipse per ghosted plane, touching all four sides. It is the first time an ellipse has to fit a space that already exists.', steps: [['Draw ghosted planes.', 'As in the planes exercise, with diagonals and centre lines.'], ['Ghost the ellipse.', 'It must touch all four edges. Decide the size and angle before drawing.'], ['Draw through twice.', 'Confident, one motion per pass.']], watch: 'Do not deform the ellipse to hit the corners. It touches the sides, not the corners.' },
  'l1-funnels': { blurb: 'Ellipses aligned to a minor axis, widening as they move out. It teaches alignment, the thing that makes cylinders believable later.', steps: [['Draw the minor axis.', 'A straight line across the page, ghosted.'], ['Draw the funnel edges.', 'Two curves that widen outward from the centre.'], ['Fill with ellipses.', 'Each one cut exactly in half by the axis, touching the curves and its neighbours.'], ['Widen the degree outward.', 'Narrow at the centre, wider at the ends.']], watch: 'The minor axis must cut every ellipse into two equal halves. Check each one.' },
  'l1-plotted': { blurb: 'Boxes drawn with a ruler toward two vanishing points. The only exercise with a ruler, so you see how convergence works before you estimate it.', steps: [['Draw the horizon and two vanishing points.', 'Three frames per page.'], ['Draw the vertical edges.', 'Any height, anywhere in the frame.'], ['Connect to the vanishing points with a ruler.', 'Draw through every box so the hidden edges show.']], watch: 'This is about seeing, not freehanding. Take your time with the ruler.' },
  'l1-rough': { blurb: 'Freehand boxes in one point perspective, then checked with a ruler. It makes the gap between what you meant and what you drew visible.', steps: [['Draw the horizon and one vanishing point.', 'Three frames per page.'], ['Draw the near face.', 'A rectangle with horizontal and vertical sides, ghosted.'], ['Estimate the receding edges.', 'They should aim at the vanishing point. Ghost, then commit.'], ['Check with a ruler.', 'Extend every receding line to the horizon. See where it missed.']], watch: 'Keep verticals vertical and horizontals horizontal. The checks are the point, not a punishment.' },
  'l1-rotated': { blurb: 'A grid of boxes rotating away from a centre one. It is meant to be hard. The goal is to think about rotation, not to succeed.', steps: [['Draw the centre box.', 'Small, with a dot for its corner.'], ['Add the neighbours.', 'Each one rotates further away. Keep them close together so their edges guide each other.'], ['Fill the ring.', 'Corners too. Draw through everything.']], watch: 'The most common mistake is not rotating at all, just sliding boxes sideways. The far ones should show more of their side.' },
  'l1-organic': { blurb: 'Boxes flowing along a curve, small and far at one end, big and close at the other. The first exercise where you decide the perspective yourself.', steps: [['Draw a flowing line.', 'Through the frame, ghosted.'], ['Place boxes along it.', 'Small ones far away, bigger ones closer. Let them overlap.'], ['Rotate them freely.', 'Every box has its own orientation. Draw through.']], watch: 'Near boxes converge harder, far boxes barely at all. Do not draw parallel edges, ever.' },

  'c250boxes-boxes': { blurb: 'Two hundred and fifty boxes, five or six to a page, each checked with line extensions. It is where spatial reasoning becomes a reflex.', steps: [['Draw a Y.', 'Three lines from one point, each angle over ninety degrees.'], ['Build the box from the Y.', 'Each new edge converges with the two it belongs to. Draw through.'], ['Extend the lines after the page.', 'Every edge, away from the viewer. See where the three sets converge.'], ['Number and date every page.', 'Fifty at a time. Take breaks between sets.']], watch: 'Lines that diverge instead of converging. Edges drawn parallel on the page. Boxes so small the arm cannot move.' },

  'l2-arrows': { blurb: 'Ribbons that twist through space and get wider as they come closer. They teach flow, and how overlapping edges tell depth.', steps: [['Draw the flow line.', 'One long curve through the frame, ghosted.'], ['Add the second edge.', 'Wider where the arrow is closer to you.'], ['Add the twist lines.', 'Where the ribbon turns over, a short curve that follows the surface.'], ['Add hatching on the turns.', 'Optional, sparingly.']], watch: 'An arrow that stays the same width is flat. Compress the far end.' },
  'l2-contour': { blurb: 'Sausages with contour ellipses on one page and contour curves on the other. The lines wrap around the form instead of sitting on it.', steps: [['Draw the sausage.', 'Two equal balls joined by a tube, ghosted.'], ['Add the ellipses.', 'Aligned to the minor axis, wider as they move away from the centre.'], ['Or the curves.', 'Only the visible half of each ellipse, hugging the surface.']], watch: 'Every ellipse must align to the axis. Curves that are all the same degree do not wrap.' },
  'l2-texture': { blurb: 'Three textures, each moving from dense on the left to empty on the right. The first is crumpled paper, drawn as bold black shapes, not lines.', steps: [['Study the reference.', 'Find the small forms that make the texture. Where do they cast shadows?'], ['Draw the shadows, not the outlines.', 'Solid black shapes. Design each one.'], ['Fade out to the right.', 'Fewer, smaller shadows until the row is empty.']], watch: 'Hatching and outlines are the mistake. Cast shadows only.' },
  'l2-dissections': { blurb: 'Textures wrapped around sausage forms so they follow the surface. It combines everything from this lesson.', steps: [['Draw the sausages.', 'A page of them, drawn through.'], ['Pick a texture per sausage.', 'From reference.'], ['Wrap it around the form.', 'Denser near the edges, lighter in the light.']], watch: 'The texture must turn with the form. If it looks pasted on, the shadow shapes are not following the ellipses.' },
  'l2-intersections': { blurb: 'Boxes, cylinders, spheres and cones intersecting in the same space. The first page is boxes only. It is hard on purpose.', steps: [['Draw the forms.', 'Same size, same foreshortening, overlapping. Draw through.'], ['Draw the intersection lines.', 'Where two surfaces meet, a line that bends with both.'], ['Add a few more forms.', 'Stop when the page is full, not when it is perfect.']], watch: 'Forms that float. Intersection lines that do not follow either surface. Wildly different foreshortening between forms.' },
  'l2-organicint': { blurb: 'Sausages piled on each other, sagging under gravity, with cast shadows. Weight and contact, not just contour.', steps: [['Draw the bottom sausage.', 'Resting on the ground.'], ['Pile the next ones.', 'Each one sags over the one below.'], ['Add contour curves and cast shadows.', 'Shadows fall onto the form below, not straight down.']], watch: 'Stiff sausages that do not bend. Shadows that ignore the shape underneath.' },

  'l3-arrows': { blurb: 'One page of organic arrows, as in Lesson 2, to warm the flow back up before plants.', steps: [['Same as Lesson 2.', 'Flow line, second edge, twists.']], watch: 'Width that does not change with distance.' },
  'l3-leaves': { blurb: 'Leaves built from a flow line and an outline, then edge detail. The flow comes first, always.', steps: [['Draw the flow line.', 'The path the leaf takes through space.'], ['Draw the leaf edges.', 'A simple shape around the flow line.'], ['Add the edge detail.', 'Jagged edges, lobes, only after the simple shape exists.']], watch: 'Detail added before the shape. Flat leaves with no flow.' },
  'l3-branches': { blurb: 'Branches as overlapping segments along a minor axis, with ellipses to keep the form round.', steps: [['Draw the minor axis.', 'The whole branch, ghosted.'], ['Add ellipses along it.', 'Aligned to the axis.'], ['Draw the edges in segments.', 'Each segment starts at one ellipse and goes past the next, so they overlap.']], watch: 'Segments that stop at each ellipse leave visible tails. Overlap them.' },
  'l3-plants': { blurb: 'Eight pages of plants from reference. The first four are construction only, no texture at all.', steps: REF, watch: REF_WATCH },
  'l4-contour': { blurb: 'Two pages of sausages with contour curves, as in Lesson 2, to prepare for insect bodies.', steps: [['Same as Lesson 2.', 'Sausage, minor axis, curves that hug the surface.']], watch: 'Curves of the same degree everywhere.' },
  'l4-construction': { blurb: 'Insects and arachnids built from solid forms, no texture or detail. Head, thorax, abdomen, then legs as sausage chains.', steps: REF, watch: REF_WATCH },
  'l4-detail': { blurb: 'Six more insects. Texture and detail allowed once the construction is solid.', steps: REF, watch: REF_WATCH },
  'l5-organicint': { blurb: 'Two pages of organic intersections, as in Lesson 2, before animals.', steps: [['Same as Lesson 2.', 'Sagging sausages, cast shadows.']], watch: 'Stiff forms.' },
  'l5-birds': { blurb: 'Two pages of birds. One of them construction only.', steps: REF, watch: REF_WATCH },
  'l5-nonhooved': { blurb: 'Two subjects, two full pages each. Wolves, cats, bears, ferrets.', steps: REF, watch: REF_WATCH },
  'l5-hooved': { blurb: 'Two subjects, two full pages each. Horses, deer, camels. Rhinos and elephants count.', steps: REF, watch: REF_WATCH },
  'l5-random': { blurb: 'Two pages of anything else. Lizards, fish, whatever you like.', steps: REF, watch: REF_WATCH },
  'l5-hybrids': { blurb: 'One page of creatures combined from references you have already studied.', steps: REF, watch: REF_WATCH },

  'c250cyl-axis': { blurb: 'Cylinders built around an arbitrary minor axis. After each page, check whether each ellipse really sits on the axis.', steps: [['Draw the minor axis.', 'Any angle, ghosted.'], ['Draw both ellipses.', 'The far one slightly wider in degree. Draw through.'], ['Connect them.', 'Two edges, ghosted.'], ['Check after the page.', 'Draw the true minor axis of each ellipse. See how far it is from yours.']], watch: 'Ellipses with the same degree at both ends. Axes that miss the ellipse centre.' },
  'c250cyl-box': { blurb: 'Cylinders inside boxes. The box comes first, with its extensions, then the ellipses in two of its faces.', steps: [['Draw the box.', 'Y method, drawn through.'], ['Find the face centres.', 'Diagonals.'], ['Draw the ellipses.', 'Touching the four edges of each face.'], ['Extend the lines after the page.', 'Box edges and the ellipse minor axes should share vanishing points.']], watch: 'Ellipses that do not touch all four sides. Minor axes that do not converge with the box.' },
  'l6-intersections': { blurb: 'Three pages of form intersections, as in Lesson 2, now with a lot more mileage behind you.', steps: [['Same as Lesson 2.', 'Mixed forms, one space, intersection lines.']], watch: 'Inconsistent foreshortening.' },
  'l6-objects': { blurb: 'Eight everyday objects with precision tools. Rulers, ellipse guides and ballpoint are welcome. Subdivide, mirror, plan.', steps: [['Draw the orthographic plans.', 'Front, side, top, with proportions worked out.'], ['Build the bounding box.', 'Subdivide it to the proportions from the plans.'], ['Carve the object out.', 'Mirroring across the centre lines.'], ['Add curves last.', 'Sparingly, with a guide if you have one.']], watch: 'Skipping the plans. Guessing proportions. Freehanding what should be precise.' },
  'c25wheels-wheels': { blurb: 'Twenty-five wheels from reference, at different angles, with an ellipse guide if you have one.', steps: [['Block in the cylinder.', 'Minor axis, two ellipses, the near one narrower.'], ['Bulge the tyre.', 'Rubber is not a straight cylinder.'], ['Add the rim and spokes.', 'Around the centre, following the ellipse.'], ['Add tread as texture.', 'Cast shadows, not lines.']], watch: 'Wheels that are straight cylinders. Spokes that do not follow the ellipse.' },
  'l7-intersections': { blurb: 'One page of form intersections to warm up.', steps: [['Same as Lesson 2.', '']], watch: '' },
  'l7-cylinders': { blurb: 'One page of cylinders in boxes with the error check.', steps: [['Same as the cylinder challenge.', 'Box, faces, ellipses, extensions.']], watch: '' },
  'l7-primitives': { blurb: 'Four pages of vehicles as primitives only. Boxes and cylinders in the arrangement of a car, drawn through, no detail.', steps: [['Pick a reference.', 'One vehicle.'], ['Place the primitives.', 'One at a time, as in form intersections.'], ['Stop.', 'No grids, no subdivision, no detail.']], watch: 'The temptation to draw the car. Draw the forms.' },
  'l7-vehicles': { blurb: 'Eight vehicles with orthographic plans. Boats, planes and wagons are welcome. Anything that carries a person.', steps: [['Draw the plans.', 'Side and front at least, with unit measurements.'], ['Build the box and subdivide.', 'To scale, from the plans.'], ['Carve the form.', 'Big masses first, wheels from the wheel challenge.'], ['Detail last.', 'Only what the construction supports.']], watch: 'Skipping the plans. Wheels that ignore the minor axis. Detail before the masses are right.' },
  'c25textures-rows': { blurb: 'Twenty-five texture analysis rows, one at a time, over weeks, in parallel with the lessons.', steps: [['One row per sitting.', 'Reference, dense to sparse, cast shadows only.'], ['Let it sit.', 'The point is time between rows, not speed.']], watch: 'Doing many rows at once. Outlines instead of shadow shapes.' },
};

export function cardFor(id) {
  return CARDS[id] || { blurb: '', steps: REF, watch: REF_WATCH };
}
